name: weeather
description: This application is for searching weather information by your location or by city name.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Http
  json_annotation: ^3.0.0
  http: ^0.12.0+4

  rxdart: ^0.24.1

  # Location
  location: ^3.0.2
  geocoder: ^0.2.1

  #Bloc
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  intl: ^0.16.1
  autocomplete_textfield: ^1.7.3

  cupertino_icons: ^0.1.3
  carousel_slider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0

  #Test
  mockito: ^4.1.1
  test: ^1.14.2


flutter:

  uses-material-design: true
  assets:
    - assets/city.list.json
